default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  pool: 10
  username: 'postgres'
  password: 'postgres'

development:
  <<: *default
  database: ems_development_one

test:
  <<: *default
  database: ems_test_one


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>